{
 "title": "Supercafe - Overall Overview",
 "tags": [ "superface" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overall volume of sales by day of week",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    CASE \n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 0 THEN 'Sunday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 1 THEN 'Monday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 2 THEN 'Tuesday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 3 THEN 'Wednesday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 4 THEN 'Thursday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 5 THEN 'Friday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 6 THEN 'Saturday'\n    END AS \"Day of Week\",\n    SUM(transactions.total_amount) AS \"Total Products Sold\"\nFROM \n    transactions\nGROUP BY \n    EXTRACT(DOW FROM transactions.\"timestamp\")\nORDER BY \n    EXTRACT(DOW FROM transactions.\"timestamp\");\n"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(total_amount)\nFROM\n  transactions;\n"
    }
   ]
  },
  {
   "title": "Most sold products - Overall",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 10, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    products.product_name AS \"Product Name\",\n    SUM(ordered_products.product_quantity) AS \"Total Orders\"\nFROM \n    ordered_products\nJOIN \n    products ON ordered_products.product_id = products.product_id\nGROUP BY \n    products.product_name\nORDER BY \n    \"Total Orders\" DESC\n\n"
    }
   ]
  },
  {
   "title": "Volume of sales per month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('month', transactions.\"timestamp\") AS \"Month\",\n    SUM(transactions.total_amount) AS \"Total Products Sold\"\nFROM \n    transactions\nGROUP BY \n    \"Month\"\nORDER BY \n    \"Month\" ASC;\n"
    }
   ]
  },
  {
   "title": "Total revenue sold per hour - broken",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('hour', transactions.\"timestamp\") AS \"Time\",\n    -- CASE \n    --     WHEN date_trunc('hour', transactions.\"timestamp\") = 9 THEN '9:00'\n    --     WHEN date_trunc('hour', transactions.\"timestamp\") = 10 THEN '10:00'\n    --     WHEN date_trunc('hour', transactions.\"timestamp\") = 11 THEN '11:00'\n    --     WHEN date_trunc('hour', transactions.\"timestamp\") = 12 THEN '12:00'\n    --     WHEN date_trunc('hour', transactions.\"timestamp\") = 13 THEN '13:00'\n    --     WHEN date_trunc('hour', transactions.\"timestamp\") = 14 THEN '14:00'\n    --     WHEN date_trunc('hour', transactions.\"timestamp\") = 15 THEN '15:00'\n    --     WHEN date_trunc('hour', transactions.\"timestamp\") = 16 THEN '16:00'\n    -- END AS \"Time\",\n    SUM(transactions.total_amount) \nFROM \n    transactions \nGROUP BY \n    \"Time\"\nORDER BY \n    \"Time\" ASC;"
    }
   ]
  },
  {
   "title": "Total Sales by Store to Date",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(total_amount), store_name \nFROM \n  transactions \nGROUP BY \n  store_name \nORDER BY \n  SUM(total_amount) DESC"
    }
   ]
  }
 ]
}