{
 "title": "Supercafe - Stores - Overall Overview",
 "tags": [ "superface-stores" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "store_name",
    "label": "Stores",
    "query": "select distinct store_name from transactions;"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume of sales by day of week",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    CASE \n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 0 THEN 'Sunday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 1 THEN 'Monday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 2 THEN 'Tuesday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 3 THEN 'Wednesday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 4 THEN 'Thursday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 5 THEN 'Friday'\n        WHEN EXTRACT(DOW FROM transactions.\"timestamp\") = 6 THEN 'Saturday'\n    END AS \"Day of Week\", \n    SUM(transactions.total_amount) AS \"Total Products Sold\"\nFROM \n    transactions\nWHERE \n    store_name = '$store_name'  \nGROUP BY \n    EXTRACT(DOW FROM transactions.\"timestamp\")\nORDER BY \n    EXTRACT(DOW FROM transactions.\"timestamp\");\n"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(total_amount)\nFROM\n  transactions\nWHERE \n    store_name = '$store_name'  ;\n"
    }
   ]
  },
  {
   "title": "Most sold products",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 10, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(ordered_products.product_quantity) AS \"ordered products\",\n    products.product_name AS \"product\", \n    transactions.store_name AS \"store\"\nFROM \n    ordered_products\nJOIN \n    products ON ordered_products.product_id = products.product_id\nJOIN \n    transactions ON ordered_products.transaction_id = transactions.transaction_id\nWHERE \n    store_name = '$store_name'\nGROUP BY \n    \"product\", \"store\"\nORDER BY\n    \"ordered products\" DESC;"
    }
   ]
  },
  {
   "title": "Volume of sales per month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('month', transactions.\"timestamp\") AS \"Month\",\n    SUM(transactions.total_amount) AS \"Total Products Sold\"\nFROM \n    transactions\nWHERE \n    store_name = '$store_name'  \nGROUP BY \n    date_trunc('month', transactions.\"timestamp\")\nORDER BY \n    \"Month\" ASC;\n"
    }
   ]
  },
  {
   "title": "Revenue over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    date_trunc('day', transactions.\"timestamp\") AS \"Time\",\n    SUM(transactions.total_amount) AS \"Revenue\"\nFROM\n    transactions\nWHERE \n    store_name = '$store_name'\nGROUP BY\n    \"Time\"\nORDER BY\n    \"Time\" ASC;"
    }
   ]
  },
  {
   "title": "Total products sold per hour",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('hour', transactions.\"timestamp\") AS \"Time\",\n    SUM(transactions.total_amount) AS \"Total Products Sold\"\nFROM \n    transactions\nWHERE \n    store_name = '$store_name'  \nGROUP BY \n    date_trunc('hour', transactions.\"timestamp\")\nORDER BY \n    \"Time\" ASC;\n"
    }
   ]
  }
 ]
}